shared worker
MutinyWallet/mutiny-web pull request #1091
Opened 2024-04-23 20:52 UTC by futurepaul

2024-04-23 21:18 UTC, benthecarman commented
in some places you do `sw.function()` and others you do `sw?.function()` what is the reasoning there?

2024-04-23 21:33 UTC, benthecarman reviewed
Everywhere where you do `// PAIN` in the worker is where we return a wasm_bindgen type instead of a `JsValue` this was supposed to be nicer for you but seems like it is worse now. Maybe in mutiny-wasm we should just try to do `JsValue` everywhere now

2024-04-23 21:33 UTC, benthecarman commented on src/router.tsx
> -            <Route path="/swaplightning" component={SwapLightning} />
Think we're only temporarily disabling these for now, should bring them back eventually

2024-04-23 21:33 UTC, benthecarman commented on src/routes/Chat.tsx
> +            console.log("item", item);
this will spam the logs

2024-04-23 21:33 UTC, benthecarman commented on src/routes/Send.tsx
> +        if (params.invoice && !state.wallet_loading) {
in other places you were checking the `load_stage === "done"`

2024-04-23 21:41 UTC, benthecarman commented
> What we have here is a [SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker).

this site says it doesn't work for chrome android :cry:, will need to test

2024-04-24 16:22 UTC, futurepaul commented
> > What we have here is a [SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker).
> 
> this site says it doesn't work for chrome android 😢, will need to test
> 
> probably should add to the screen where we detect if js/wasm is enabled, that shared workers are available

THIS IS SO SAD :(. It's a one line change to make it a non-shared worker, but I might look into detecting Chrome Android specifically so we can use sharedworker other places. But that means I need to bring back all the double init defense stuff :(

I'm also having trouble with capacitor right now. It's not working iOS or Android, for what might be different reasons. One problem is this `import.meta.url` which doesn't seem to exist in the Capacitor environment, trying to figure it out.

2024-04-24 16:58 UTC, futurepaul commented
Got android working...

<img width="732" alt="Screenshot 2024-04-24 at 11 35 12 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/6099b9ab-5034-4924-ae25-b92980ef93b3">

But iOS is mad about something. Works in desktop safari...

<img width="505" alt="Screenshot 2024-04-24 at 11 37 07 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/8ccda9c9-c76d-4f8c-a8ef-de12a3975a84">

2024-04-25 17:58 UTC, futurepaul commented
> Everywhere where you do `// PAIN` in the worker is where we return a wasm_bindgen type instead of a `JsValue` this was supposed to be nicer for you but seems like it is worse now. Maybe in mutiny-wasm we should just try to do `JsValue` everywhere now

yeah it sucks because the JsValue erases the type so I have to go digging to figure out what it's actually returning. do you remember why this was rejected btw? https://github.com/MutinyWallet/mutiny-node/pull/882

2024-04-25 18:04 UTC, benthecarman commented
Wasm bindgen does the same thing, it just doesn't work for async functions yet. I think they recently merged support for it though

2024-05-02 20:34 UTC, TonyGiorgio commented
My mainnet tests on my android phone are great. No more flicker. Page switches are much faster now. Signet will need a full end to end test but this is really smooth. Nice work!

2024-05-02 21:35 UTC, TonyGiorgio commented
<img width="658" alt="Screenshot 2024-05-02 at 4 34 57 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/101225832/5e50ce91-40a7-462f-a185-404520e1a6ee">

I don't think it's intended to be at the bottom?

2024-05-06 19:57 UTC, TonyGiorgio requested changes

2024-05-06 19:57 UTC, TonyGiorgio commented on package.json
> +    "version": "0.6.9",
regenerate package.lock

2024-05-06 20:00 UTC, TonyGiorgio approved these changes

2024-05-06 20:00 UTC, merged