show federation expiration metadata
MutinyWallet/mutiny-web pull request #1129
Opened 2024-05-07 15:23 UTC by futurepaul

for #1128 

here's what I have so far. putting this here so @TonyGiorgio can see the logic I used to get the metadata

<img width="408" alt="Screenshot 2024-05-07 at 10 22 03 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/5e6fa522-cf1f-45cc-9f1a-bb4cf457438e">

2024-05-08 01:17 UTC, TonyGiorgio commented
1. It's not obvious what I'm supposed to do after the "Manage Federations" pop up window comes up. I think if the "transfer funds" button stayed on the federation page no matter what, it would be more obvious. A popup could come up, saying whether they want to swap to lightning or swap to a new federation and they should add one if they have it?

2. When the federation is the 2nd one, the pop up doesn't happen.

2024-05-08 21:50 UTC, futurepaul commented
needs https://github.com/MutinyWallet/mutiny-node/pull/1169 and a new version of mutiny node

2024-05-09 01:43 UTC, benthecarman commented on src/routes/Transfer.tsx
> +    });
this doesn't seem useful

2024-05-09 01:43 UTC, benthecarman commented on src/routes/Transfer.tsx
> +    // const fromFederatationId = params.from;
ping

2024-05-09 01:50 UTC, TonyGiorgio approved these changes

2024-05-09 01:52 UTC, benthecarman commented on src/components/AmountEditable.tsx
> +        return "community";
you have a comment here saying to add fedimint, you can remove that now.

also would be better as a switch than if statements

2024-05-09 02:09 UTC, benthecarman approved these changes

2024-05-09 03:37 UTC, TonyGiorgio requested changes
Needs retest

2024-05-09 16:58 UTC, futurepaul commented
looks good now @TonyGiorgio

2024-05-09 18:39 UTC, TonyGiorgio approved these changes
Works great, just a nit that the federation name in the popup would be useful.

2024-05-09 18:49 UTC, merged