amount input switchable to usd
MutinyWallet/mutiny-web pull request #192
Opened 2023-05-31 21:39 UTC by futurepaul

<img width="305" alt="Screenshot 2023-05-31 at 4 38 45 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/d3f45da6-3744-4829-9830-1ef8feb0e23b">

2023-05-31 21:52 UTC, benthecarman requested changes
The fiat to sats conversion doesn't seem to work anymore

![image](https://github.com/MutinyWallet/mutiny-web/assets/15256660/e889127b-362e-40d4-bb95-58be066643f2)

2023-05-31 21:52 UTC, benthecarman commented on src/components/AmountEditable.tsx
> +                // class="opacity-0 absolute -z-10"
nit: can remove this i think

2023-05-31 21:53 UTC, benthecarman commented
Also not sure I love the way to switch between fiat and sats, normally you would just click the fiat number. I only really knew the swap button was the button for this because I was reviewing the PR

2023-05-31 22:45 UTC, futurepaul commented on src/components/AmountEditable.tsx
> +                // class="opacity-0 absolute -z-10"
thx

2023-05-31 22:46 UTC, futurepaul commented
okay updated with tap the amount to switch... also the price api seems to have been weird recently, can you try again?

btw you have to start on the home screen and then go to the receive screen to get price data... not exactly sure why. I checked and the same thing is true for the existing amount input screen

2023-06-01 17:44 UTC, TonyGiorgio commented
When I type in a few numbers, tap the switch and try typing more numbers, it does not work.

2023-06-02 16:23 UTC, futurepaul commented
> When I type in a few numbers, tap the switch and try typing more numbers, it does not work.

okay this was a very helpful comment I realized I can just always let the person keep typing in fiat view and just shift the decimal... before I was deleting anything the user typed past two decimals which is what you were seeing when you entered some sats then switched to fiat

2023-06-02 16:40 UTC, TonyGiorgio commented
Looks and works great!

2023-06-02 16:53 UTC, benthecarman approved these changes

2023-06-02 16:53 UTC, merged