Send button now checks for insufficientFunds()
MutinyWallet/mutiny-web pull request #195
Opened 2023-06-01 19:58 UTC by benalleng

Depending on the source the user selected the send button checks their balance against the amountSats() sent to determine if the button should be disabled.

Closes #97

2023-06-01 21:54 UTC, futurepaul requested changes
nice improvement!

please squash your commits into a single commit and make sure to run prettier, there's a prettier config that prettier should pick up

2023-06-01 21:54 UTC, futurepaul commented on src/routes/Send.tsx
> +      return (state.balance?.confirmed ?? 0n) < amountSats()
should be the sum of confirmed + unconfirmed (I recently learned you can send from unconfirmed, changed my life)

2023-06-04 19:20 UTC, benalleng commented
With the introduction of #202 sending onchain now presents a clear error when the user has insufficient funds but lightning does not. Going to go ahead and make a new issue to address @benthecarman comment from element

> Would be confusing to enter an amount and can't figure out why I can't press the send button

> Yeah maybe putting some red error message under the amount saying insuffienct funds would make it better

2023-06-05 13:58 UTC, benalleng commented
Going to make a new PR, I messed up the rebase and now the history is totally borked

2023-06-05 14:04 UTC, closed without merging