Add network subheading
MutinyWallet/mutiny-web pull request #223
Opened 2023-06-06 19:46 UTC by benalleng

Closes #172

shows a network subheading when not on mainnet

![image](https://github.com/MutinyWallet/mutiny-web/assets/108441023/3baf59c9-a65f-475f-bc34-131b7a3310f9)

2023-06-07 00:00 UTC, futurepaul requested changes
how about taking the styling from the `<Indicator />` component minus the pulse animation and putting it below the logo?

also the best way to get the network is `const network = state.mutiny_wallet?.get_network()`

and thirdly I think this should only show if on testnet / signet / regtest. so `<Show when={network !== "bitcoin"}>`

2023-06-16 20:14 UTC, benalleng commented
I had some difficulty setting the network as a variable as it would be called before the wallet was no longer state.wallet_loading so i went with just directly calling the get network after the `<Show />` conditions were met

2023-06-16 20:17 UTC, benalleng commented
Lastly any desire to make a non-flashing <Indicator /> for future use in this PR?

2023-06-19 22:06 UTC, futurepaul requested changes
sweet just one tiny thing

2023-06-19 22:06 UTC, futurepaul commented on src/components/App.tsx
> +                    <div class="flex flex-col justify-center">
```suggestion
                    <div class="flex flex-col justify-center gap-2">
```

2023-06-19 22:08 UTC, futurepaul commented
> Lastly any desire to make a non-flashing `<Indicator />` for future use in this PR?

good thought but can hold off for now, we're about to have a wholistic figma ui as reference so that can be a time to revisit the "componentization" of some of this stuff (I don't think there's any Indicator in the new design)

2023-06-20 15:32 UTC, futurepaul approved these changes
thank you!

2023-06-20 15:32 UTC, merged