Closing on Amount choice returns you to homepage instead of continuing to next step
MutinyWallet/mutiny-web pull request #258
Opened 2023-06-16 21:42 UTC by benalleng

Closes #205

2023-06-16 21:45 UTC, benalleng commented
realized this isn't useable for the send route converting to draft

2023-06-20 21:21 UTC, futurepaul requested changes
tested a few flows and this all seems to be working correctly to me. thanks for tackling! just one little refactor

2023-06-20 21:21 UTC, futurepaul commented on src/components/AmountEditable.tsx
> +                        onEscapeKeyDown={() => {
looks like this logic is identical to the close button, could probably pull it out as a function that gets used in both?

2023-06-21 22:43 UTC, futurepaul submitted a review, later dismissed
big win, thank you!

2023-06-21 22:55 UTC, futurepaul approved these changes

2023-06-21 22:56 UTC, merged