WIP mutiny plus
MutinyWallet/mutiny-web pull request #314
Opened 2023-07-04 02:10 UTC by futurepaul

2023-07-06 20:40 UTC, futurepaul commented
this is based on mutiny-node master rn but otherwise is pretty close I think

2023-07-07 17:15 UTC, TonyGiorgio commented
![Screenshot from 2023-07-07 12-13-02](https://github.com/MutinyWallet/mutiny-web/assets/101225832/06f77aee-3b8a-4e59-b144-9a4e36679d6b)

There's no information about price on the main screen and this warning dialog makes it seem like they would immediately pay, but there's no pricing information. This warning about "are you sure" doesn't make sense because not enough information was given for them to make a decision.

2023-07-07 17:18 UTC, TonyGiorgio commented
When I attempt to join when no balance, I get an `We do not have enough balance to pay the given amount.` error. 

We should tell them upfront that they need to fund the wallet first before paying.

2023-07-07 17:20 UTC, TonyGiorgio commented
There's so much text here, would be nice if there's at least more indication and seperation around the price. It blends in to all the text. 

![Screenshot from 2023-07-07 12-19-53](https://github.com/MutinyWallet/mutiny-web/assets/101225832/cfbc9cc4-9936-440c-8964-010e312fd973)

2023-07-07 17:22 UTC, TonyGiorgio commented on src/routes/settings/Plus.tsx
> +                                    You'll get a renewal payment request on{" "}
```suggestion
                                    You'll get a renewal payment request around {" "}
```

2023-07-07 17:25 UTC, TonyGiorgio commented
I like the `+` icon!  

![Screenshot from 2023-07-07 12-23-39](https://github.com/MutinyWallet/mutiny-web/assets/101225832/362d4813-a4b2-4c8e-bb91-b6a4393bbe4e)

2023-07-07 18:28 UTC, TonyGiorgio commented on src/routes/settings/Plus.tsx
> +                Easy gifting <em>(coming soon)</em>
```suggestion
                Gifting <em>(coming soon)</em>
```

I think just calling it gifting is better.

2023-07-07 19:02 UTC, TonyGiorgio requested changes
Some minor things to make sure this is solid and the edge cases are handled but everything else like restoring or expiration handling seems to work pretty well!

2023-07-08 00:13 UTC, futurepaul commented
alright should be ready for another look

2023-07-08 19:31 UTC, TonyGiorgio commented
Needs rebase.

2023-07-08 20:13 UTC, TonyGiorgio requested changes
Testing works pretty well, just a few code things I noticed.

2023-07-08 20:13 UTC, TonyGiorgio commented on src/components/Activity.tsx
> +            console.log("Syncing activity...");
This can be removed, a bit spammy in the logs.

2023-07-08 20:13 UTC, TonyGiorgio commented on src/components/App.tsx
> +                            <Match when={state.subscription_timestamp}>
I think there should be a function checking whether `state.subscription_timestamp` is not expired yet.

We can do a ~3 day grace period thing in a future PR later this month. But until then, all of the checks on this valud should also check whether or not it is in the past.

2023-07-08 20:13 UTC, TonyGiorgio commented on src/routes/settings/Plus.tsx
> +            const invoice = await state.mutiny_wallet?.subscribe_to_plan(0);
it should just be `planDetails().id`

2023-07-08 22:42 UTC, TonyGiorgio requested changes

2023-07-08 22:42 UTC, TonyGiorgio commented on src/routes/settings/Plus.tsx
> +                            <Match when={state.subscription_timestamp}>
check expired

2023-07-08 22:42 UTC, TonyGiorgio commented on src/routes/settings/Plus.tsx
> +                            <Match when={!state.subscription_timestamp}>
check expired

2023-07-08 22:56 UTC, futurepaul commented
nice catches ty

2023-07-08 23:26 UTC, TonyGiorgio approved these changes

2023-07-08 23:31 UTC, TonyGiorgio commented
needs rebase

2023-07-08 23:33 UTC, merged