VSS config
MutinyWallet/mutiny-web pull request #324
Opened 2023-07-11 21:13 UTC by benthecarman

will be needed for next release

2023-07-11 21:44 UTC, futurepaul commented
is there a url we can put in the .env.example?

2023-07-11 23:14 UTC, TonyGiorgio commented
This text can be removed: `Beta warning: you can currently only restore on-chain funds. Lightning backup restore is coming soon.`

great fucking work, testing it now.

2023-07-12 04:23 UTC, TonyGiorgio commented on package.json
> +        "@mutinywallet/mutiny-wasm": "0.4.1",
version the package.json at the top as well

2023-07-12 04:24 UTC, TonyGiorgio requested changes
nit, otherwise gtg

2023-07-12 04:26 UTC, TonyGiorgio approved these changes

2023-07-12 04:26 UTC, merged