Handle android app links
MutinyWallet/mutiny-web pull request #485
Opened 2023-08-23 01:58 UTC by TonyGiorgio

2023-08-23 03:57 UTC, TonyGiorgio commented on android/app/src/main/AndroidManifest.xml
> +            <tools:validation testUrl="https://android-app-links.mutiny-web.pages.dev/" />
TODO: remove this

2023-08-23 03:58 UTC, TonyGiorgio commented on android/app/src/main/AndroidManifest.xml
> +                    android:host="android-app-links.mutiny-web.pages.dev"
TODO: switch to app.mutinywallet.com

2023-08-23 04:02 UTC, TonyGiorgio commented
This kind of works. I might need some help with two different problems: 

1. I don't think `App.tsx` lives forever. I get unmounts / cleanups whenever I move to the settings page, and if I minimize the app on the settings page and click on a url like `app.mutinywallet.com/settings/connections?callbackUri=primal&name=Primal` then it does not load the connections page. Is there a better place for these long lived global listeners to stay? 
2. The `Connections.tsx` page is not loading the query parameters if the app was already opened. I have verified that the `navigate` is working properly, but `name` is null on `Connection.txs`. If I force close the app and click on a link with query parameters, those make it across properly. 

Tried a bunch of random little things but couldn't get it working for these.

2023-08-23 19:33 UTC, benthecarman commented on src/components/App.tsx
> -    // Check if the platform is Android to handle back
are you removing this on purpose?

2023-08-23 19:34 UTC, benthecarman commented on src/components/App.tsx
> -    // Check if the platform is Android to handle back
oh nvm, i see you moved it

2023-08-23 19:37 UTC, benthecarman reviewed
the web links still work, otherwise can't review much else

2023-08-24 18:37 UTC, benalleng reviewed
tested on Pixel 4a using the debug.apk

with apps:

https://github.com/MutinyWallet/mutiny-web/assets/108441023/44ad87f0-c581-4012-aff6-6b3d2c2fdd8b

without apps:

https://github.com/MutinyWallet/mutiny-web/assets/108441023/89ae54f6-ee04-46a1-bd9b-bb249c070bf1

2023-08-25 18:46 UTC, TonyGiorgio commented
> How should I test this after downloading the debug.apk?

click a link with https://app.mutinywallet.com and it should open the app. Click a link with https://app.mutinywallet.com/settings/connections?callbackUri=primal&name=Primal and it will open the connections page with a box to fill it in. 

However, it does require going into android settings > app > mutiny > default links and turning on https://app.mutinywallet.com because it doesn't have the deployed well known app links thing yet.

2023-08-25 20:28 UTC, benalleng reviewed
https://github.com/MutinyWallet/mutiny-web/assets/108441023/32833020-0259-4577-ad00-ab2998c8430e

Looks like almost all links work! small inconsistency in Primal

2023-08-25 22:08 UTC, TonyGiorgio commented on android/app/src/main/AndroidManifest.xml
> +                    android:pathPattern="/.*" />
Interesting! It's just from the primal app that the URL doesn't open up the app when it doesn't have the forward slash at the end? It opens up from other apps?

2023-08-25 23:01 UTC, benalleng commented on android/app/src/main/AndroidManifest.xml
> +                    android:pathPattern="/.*" />
on testing it looks like amethyst does the same thing, at least with those 2 links. It worked with no forward slash on github from the link you posted. gonna test them here.

https://app.mutinywallet.com
https://app.mutinywallet.com/

2023-08-25 23:14 UTC, TonyGiorgio commented on android/app/src/main/AndroidManifest.xml
> +                    android:pathPattern="/.*" />
I added another intent link for one without a `/` at all to see if that helps.

2023-08-25 23:39 UTC, benalleng commented on android/app/src/main/AndroidManifest.xml
> +                    android:pathPattern="/.*" />
hmm unfortunately, it doesn't seem to work. Though going through a bunch of different apps on my phone I am now convinced no-one really fully understands how to set them up properly, linkedin can't figure it out either lol

2023-08-26 11:30 UTC, benalleng requested changes
I think I figured it out, tested on my test PR #493 and it works!

2023-08-26 11:30 UTC, benalleng commented on android/app/src/main/AndroidManifest.xml
> +            </intent-filter>
Figured it out. I believe the data needs to be separate for it to work, additionally on my Android copying or opening any link like [app.mutinywallet.com](http://app.mutinywallet.com) adds `http://` not `https://` in front in the clipboard. I suggest we try something like this.

```suggestion
<intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="https"
                    android:host="app.mutinywallet.com" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="http"
                    android:host="app.mutinywallet.com" />
            </intent-filter>
```

2023-08-28 17:45 UTC, TonyGiorgio commented
Thanks @benalleng! Yeah that sounds right. I was hesitant to test the different path version one just out of laziness but I had seen that suggestion as well. Wasn't sure if it was going to make a different. But yeah I did read on spliting the intents before so good catch there.

2023-08-28 18:32 UTC, benalleng approved these changes
Still have one stray import warning but other than that it LGTM!

2023-08-28 20:47 UTC, futurepaul approved these changes
works great tested on device, and the `.well-known/assetlinks.json` seems like it deploys to the right place

2023-08-28 20:47 UTC, futurepaul commented on src/root.tsx
> +import { onCleanup } from "solid-js";
need to merge this import with the one above... tbh odd that `pnpm run format` isn't doing this automatically

2023-08-28 20:47 UTC, futurepaul commented on src/root.tsx
> +    return null;
this is so weird to me to make a null component but seems to work so not gonna fight it!

2023-08-28 20:59 UTC, merged