wip multi lsp
MutinyWallet/mutiny-web pull request #767
Opened 2023-12-12 20:20 UTC by futurepaul

my version of #748

relies on https://github.com/MutinyWallet/mutiny-node/pull/894

I think we might need some better facility for "switching" lsp in mutiny-node. We can't make the lsps stuff default yet, so that means a wallet and node spin up at launch with flow 2.0 and apparently that locks the wallet to only using the original lsp that's set.

2023-12-14 23:24 UTC, TonyGiorgio commented
> I think we might need some better facility for "switching" lsp in mutiny-node. We can't make the lsps stuff default yet, so that means a wallet and node spin up at launch with flow 2.0 and apparently that locks the wallet to only using the original lsp that's set.

Could you expand upon this? I think it's a reasonable assumption to have voltage flow2.0 as the assumption right now. Basicaly we set the default URL in the config right like the other configs?

2023-12-18 18:37 UTC, futurepaul commented
Yeah I agree, the problem is if the wallet fires up with flow 2.0 (which happens on load) there's not a good way to change it. Right now it only works if you set it up initially with one or the other (the testing so far has been to change the default, trying to figure out how to do it without it being the default).

2023-12-18 18:38 UTC, TonyGiorgio commented
I'm not sure why it's not handled like every one of our other configs that the user can change.

2023-12-18 18:48 UTC, futurepaul commented
I think it's because once the node is set up it's locked to that lsp?

2023-12-18 18:50 UTC, benthecarman commented
We probably need a `change_lsp` function so we can change it from the default. Just need it to error if there are any active channels

2023-12-20 22:20 UTC, futurepaul commented
alright I believe this is working now with https://github.com/MutinyWallet/mutiny-node/pull/904

I can switch lsp successfully and I see the new peer to the c= node. only problem is I haven't gotten a receive to work yet not sure if that's our faucet or the c= lsp status or what

2023-12-21 19:48 UTC, futurepaul commented
to test this go to https://multi-lsp-alpha.mutiny-web.pages.dev/settings/admin and delete the LSP entry and use these two values

LSPS_CONNECTION_STRING: `0371d6fd7d75de2d0372d03ea00e8bacdacb50c27d0eaea0a76a0622eff1f5ef2b@3.84.56.108:39735`

LSPS_TOKEN: `cequals21jit`

2023-12-21 20:01 UTC, benthecarman requested changes

2023-12-21 20:19 UTC, benthecarman approved these changes

2023-12-21 20:19 UTC, futurepaul commented on src/logic/mutinyWalletSetup.ts
> +    },
okay I did this and I tested with and without those env vars set and with and without an existing channel seems to do the right thing in both cases

2023-12-21 20:22 UTC, merged