add delete nostr profile ability
MutinyWallet/mutiny-web pull request #970
Opened 2024-03-28 17:38 UTC by futurepaul

needs https://github.com/MutinyWallet/mutiny-node/pull/1096

2024-03-28 17:44 UTC, benthecarman commented on src/routes/settings/NostrKeys.tsx
> +            console.log("yooo");
don't need tihs console log

2024-03-28 17:44 UTC, benthecarman commented on src/routes/settings/NostrKeys.tsx
> +            await state.mutiny_wallet?.delete_profile();
should delete the local nsec if one is imported too

2024-03-28 18:03 UTC, benthecarman approved these changes
works for me

2024-03-28 18:54 UTC, TonyGiorgio requested changes
Importing an nsec after deleting the main wallet nsec doesn't work.

2024-03-28 19:39 UTC, futurepaul commented
> Importing an nsec after deleting the main wallet nsec doesn't work.

It works for me. I made a new profile with a new wallet, deleted the profile, and then imported my normal nsec.

2024-03-28 22:50 UTC, benthecarman commented on src/routes/Profile.tsx
> +        }
this can just be `(profile().deleted === true || profile().deleted === "true")` no need for the if statement

2024-03-28 23:16 UTC, benthecarman approved these changes
Paul and I tested every case we could think of on a call, this is good to go

2024-03-29 00:32 UTC, TonyGiorgio approved these changes

2024-03-29 00:32 UTC, TonyGiorgio approved these changes

2024-03-29 00:32 UTC, merged